CRM_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("crmapp.urls", namespace="leads"))
]

urlpatterns+=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

crmapp/urls.py
from django.urls import path
from . import views

app_name="leads"

urlpatterns = [
    path('leads-view/',views.view,name='view'),
    path('leads-details/<str:pk>/', views.details, name='details'),
    path('leads-create/', views.create, name='create'),
]

crmapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.email

class Lead(models.Model):
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE)
    first_name=models.CharField(max_length=20, null=True, blank=True)
    last_name=models.CharField(max_length=20, null=True, blank=True)
    age=models.IntegerField(default=0)
    image=models.ImageField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

crmapp/forms.py
from django import forms
from . models import Lead

class LeadCreateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = '__all__'

crmapp/views.py
from django.shortcuts import render,redirect
from . models import Lead, Agent, User
from . forms import LeadCreateForm
from django.contrib import messages

def view(request):
    lead = Lead.objects.all()
    return render(request, 'leads-view.html', {'lead':lead})

def details(request, pk):
    lead = Lead.objects.get(id=pk)
    return render(request, 'leads-details.html', {'lead':lead})

def create(request):
    form = LeadCreateForm()
    
    if request.method == 'POST':
        form=LeadCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('leads:view')
        else:
            messages.info(request,'unsuccessful')
            return redirect('leads:view')
    
    else:
        return render(request, 'leads-create.html', {'form':form})

crmapp/templates/leads-create.html
<style>
    h5{
        color: red;
    }
</style>

<h1>HELLO</h1>
<form method="POST" action="">
    {% for message in message %}
<h5>{{message}}</h5>
{% endfor %}
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

crmapp/templates/leads-details.html
<h1>HELLO</h1>

<ul>
    <li>
        <img src="{{lead.image.url}}">
        <h3>{{lead.first_name}} {{lead.last_name}}</h3><br>
        <h3> age: {{lead.age}}</h3><br>
        <h3>agent: {{lead.agent}}</h3><br>
    </li>
</ul>

crmapp/templates/leads-view.html
<h1>HELLO</h1>
<ul>
    {% for lead in lead %}
    <li>
        <img src="{{lead.image.url}}"> <br>
        
        <a href="{% url 'leads:details' lead.pk %}"><h3>{{lead.first_name}}{{lead.last_name}}</h3></a>
        
        {% empty %}
        <h1>MMMMMMM no Leads at this time</h1>
        
    </li>
    {% endfor %}
</ul>
<a href="{% url 'leads:create' %}"><h3>Add a Lead</h3></a>